
/* File autogenerated by generate_functions.py
 * Do not edit manually or check into VCS.
*/

#define NO_IMPORT_ARRAY
#define PY_ARRAY_UNIQUE_SYMBOL _crappy

#include "sparsetools.h"
#include "example.h"

extern "C" {
        #include "example_impl.h"
}